### PR TITLE
Fix #89 by using cookies when localstorage is unavailable

### LINKED ISSUE #89: Access denied error in IE
IE with Protected mode enabled throw Access denied error when you try to use localstorage. I guess it's good idea to check if you can use localstorage. And if you can't - use cookies instead

### PR DESCRIPTION
**Pull request by digitclue**

### CODE REVIEW

**Comment by karthilxg** [comment]
Added fallback for localstorage https://github.com/HackedByChinese/ng-idle/pull/112

**Comment by astopo** [comment]
Woohoo!

**Comment by HackedByChinese** [comment]
I appreciate the contribution... I'll bring it in when I figure out how to make optional dependencies.

**Comment by karthilxg** [comment]
@HackedByChinese :+1:

**Pull request closed without merging**
