### PR TITLE
webkit-fake-mousemove-fix patch

### PR DESCRIPTION
**Pull request by RevanProdigalKnight**
I applied the patch to all browsers mindlessly, it turns out that "event.movementX" and "event.movementY" are Webkit-specific event properties.

I apologize for my mistake. Please be merciful.

### CODE REVIEW

**Comment by HackedByChinese** [comment]
Hmm, this has reminded me I still don't have coverage in the unit tests for DOM events triggering the interrupt :(

**Comment by RevanProdigalKnight** [comment]
I need to figure out how to do that for the webapp I'm making, so if you haven't added any by the time I start making those, I'll create a pull request to add them.

**Comment by HackedByChinese** [comment]
I do have a test, but it's commented out (see https://github.com/HackedByChinese/ng-idle/blob/develop/src/idle/idle.spec.js#L389) because of the reasons mentioned in the comment. I (or someone) just need to figure out the deal with that and then we're covered. However, we'll want to add another test to cover WebKit, which prompts the suggestion that we change your commit to not reference `navigator` directly, but try to access it off `$window` so it is more easily unit tested.

**Comment by RevanProdigalKnight** [comment]
I've changed the code to use the `$window` object so that when one of us figures out how to fix the unit tests there will be no compatibility issues.

**Comment by joero4** [comment]
I think I have fixed that unit test.  I could be wrong, but it's in my pull request.  I have two unit tests which covers the standard interrupts, and also one which covers my use case for uninterrupting.  I know the tests have passed, but I'm a bit of a noob when it comes to angular unit testing so be gentle if you find something wrong with it.

**Comment by RevanProdigalKnight** [comment]
@joero4 I think he's referring more to the fact that we need unit tests for all the interrupt events in order to check for bugs in at least the major browsers, but if your unit tests pass then maybe we should use them as an example for further expansion of unit tests.

**Comment by joero4** [comment]
They do pass, and testing only the 'mousedown' event right now.  It's simply a jquery trigger of the event, so no real browser testing.  

The comment in the code in the test is...
```javascript
// HACK: the body event listener is only respected the first time, and thus always checks the first Idle instance we created rather than the one we created last.
      // in practice, the functionality works fine, but here the test always fails. dunno how to fix it right now.
```
I'm not sure I understand his note on checking he first instance vs the last.  Maybe it's my lack of understanding for angular unit tests.  Also his test failed, but I found some errors in the code, which I think was due to some older code which was updated, but the test was never updated to reflect the updates.  Just a guess though.  Either way the test now passes, and seems to work as expected.

**Comment by HackedByChinese** [comment]
A more recent set of changes to address this issue will supercede this PR.

**Pull request closed without merging**
