### PR TITLE
Allow title changes to be disabled through configuration

### PR DESCRIPTION
**Pull request by ruipenso**
I found useful to disable title changes through configuration instead of adding `idle-disabled="true"` to the title tag.

WDYT?

### CODE REVIEW

**Comment by ruipenso** [comment]
BTW, I'm having issue running the test suite, even in `master`. I just installed the dependencies and ran the tests.

```
$ npm install
$ bower install
$ npm run-script test
```

Am I missing something?

**Comment by HackedByChinese** [comment]
It should all be on the readme. You will need to install grunt-cli separately, but then just run NPM install and then grunt test.

**Comment by ruipenso** [comment]
I've done that. Take a look at this [sample log](https://gist.github.com/ruipenso/9f887108d249bab98895).

**Comment by HackedByChinese** [comment]
I cleaned and reran the install, but got totally different errors because the version of node/npm is more recent, and karma is out of date.

I'll take a look at your suggestions and if we're good to go, it's going to get merged to develop (not master; I use git-flow here).

**Comment by HackedByChinese** [comment]
This has been merged to develop (so, not released yet).

**Comment by ruipenso** [comment]
@HackedByChinese Ok. Thanks.

**Comment by toxaq** [comment]
Has this been released? I'd prefer to disable the title change in the config too. It seems a little arbitrary to hijack the title and not anything else. I never see anything but the first 5 letters of a page title in a tab anyway!

**Pull request closed without merging**
