### PR TITLE
Unwatch when autoresuming

### PR DESCRIPTION
**Pull request by philipbjorge**
Hey @HackedByChinese ,
We have a use-case that requires a user interrupt to unwatch.
Here is our implementation + specs.

Do you have any interest in accepting this upstream? I'd happily update the docs.
Any more info you need from us?

### CODE REVIEW

**Comment by HackedByChinese** [comment]
So this is like a reverse idle?

**Comment by philipbjorge** [comment]
We're using it for playing notification sounds:
1. When a notification comes in, we play a sound and start Idle.
2. If the user gets into IdleStart after 5 minutes, we play a reminder notification.

What the unwatch ability lets us do is upon receiving a user interrupt we can now treat the original notification as "seen" and avoid sending a reminder notification.

**Comment by philipbjorge** [comment]
I think we sent this PR a little early... We have one more issue to work through that might not be upstream compatible. I'll get back to you.

**Comment by philipbjorge** [comment]
@HackedByChinese -- This is ready for consideration now.

**Pull request closed without merging**
